package network

import (
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"time"
)

var ErrInvalidDeviceStatus = errors.New("invalid network device status")

type Service struct {
	repository *Repository
	collector  *Collector
	config     Config
}

func NewService(repository *Repository, config Config) *Service {
	return &Service{
		repository: repository,
		collector:  NewCollector(config),
		config:     config,
	}
}

func (s *Service) Snapshot(ctx context.Context) (Snapshot, error) {
	devices, sources := s.collector.Devices(ctx)
	if err := s.repository.UpsertDiscovered(ctx, devices); err != nil {
		return Snapshot{}, err
	}
	decisions, err := s.repository.ListDecisions(ctx)
	if err != nil {
		return Snapshot{}, err
	}
	devices = mergeDecisions(devices, decisions)
	visits, dnsSource := s.collector.Visits(ctx, devices, 100)
	sources = append(sources, dnsSource)

	overview := buildOverview(devices, visits, sources, s.config.BlocklistPath)
	return Snapshot{Overview: overview, Devices: devices, Visits: visits}, nil
}

func (s *Service) UpdateDevice(ctx context.Context, id string, request UpdateDeviceRequest) (Device, error) {
	request.Status = strings.TrimSpace(request.Status)
	if request.Status != "" && !validStatus(request.Status) {
		return Device{}, ErrInvalidDeviceStatus
	}
	device, err := s.repository.Update(ctx, id, request)
	if err != nil {
		return Device{}, err
	}
	if err := s.writeBlocklist(ctx); err != nil {
		return Device{}, err
	}
	return device, nil
}

func (s *Service) writeBlocklist(ctx context.Context) error {
	if s.config.BlocklistPath == "" {
		return nil
	}
	decisions, err := s.repository.ListDecisions(ctx)
	if err != nil {
		return err
	}
	blocked := make([]Device, 0)
	for _, device := range decisions {
		if device.Status == DeviceStatusBlocked {
			blocked = append(blocked, device)
		}
	}
	slices.SortFunc(blocked, func(a, b Device) int {
		return strings.Compare(a.IP, b.IP)
	})
	if err := os.MkdirAll(filepath.Dir(s.config.BlocklistPath), 0o755); err != nil {
		return fmt.Errorf("create network blocklist dir: %w", err)
	}
	var builder strings.Builder
	builder.WriteString("# Generated by HomeLab network monitor\n")
	builder.WriteString("# Use this list from your router/firewall/DNS stack to enforce blocks.\n")
	for _, device := range blocked {
		builder.WriteString(fmt.Sprintf("%s %s %s\n", device.MAC, device.IP, device.Name))
	}
	if err := os.WriteFile(s.config.BlocklistPath, []byte(builder.String()), 0o644); err != nil {
		return fmt.Errorf("write network blocklist: %w", err)
	}
	return nil
}

func mergeDecisions(live []Device, decisions map[string]Device) []Device {
	seen := map[string]bool{}
	for index, device := range live {
		decision, ok := decisions[device.ID]
		if ok {
			device.Name = decision.Name
			device.Status = decision.Status
			device.Note = decision.Note
			device.FirstSeen = decision.FirstSeen
			if decision.LastSeen.After(device.LastSeen) {
				device.LastSeen = decision.LastSeen
			}
			live[index] = device
		}
		seen[device.ID] = true
	}
	for id, device := range decisions {
		if seen[id] || device.Status == DeviceStatusIgnored {
			continue
		}
		device.Source = "DB"
		live = append(live, device)
	}
	slices.SortFunc(live, func(a, b Device) int {
		if a.Status == b.Status {
			return strings.Compare(a.IP, b.IP)
		}
		return strings.Compare(a.Status, b.Status)
	})
	return live
}

func buildOverview(devices []Device, visits []Visit, sources []Source, blocklistPath string) Overview {
	overview := Overview{
		GeneratedAt:   time.Now().UTC(),
		DevicesTotal:  len(devices),
		LiveSources:   sources,
		BlocklistPath: blocklistPath,
	}
	for _, device := range devices {
		if device.Status == DeviceStatusIgnored {
			continue
		}
		if time.Since(device.LastSeen) < 10*time.Minute || device.Source != "DB" {
			overview.DevicesOnline++
		}
		switch device.Status {
		case DeviceStatusUnknown:
			overview.DevicesUnknown++
		case DeviceStatusBlocked:
			overview.DevicesBlocked++
		}
	}
	for _, visit := range visits {
		overview.RecentVisits++
		if visit.Action == "blocked" {
			overview.BlockedVisits++
		}
	}
	if info, err := os.Stat(blocklistPath); err == nil {
		updatedAt := info.ModTime().UTC()
		overview.BlocklistUpdatedAt = &updatedAt
	}
	return overview
}

func validStatus(status string) bool {
	return status == DeviceStatusUnknown ||
		status == DeviceStatusTrusted ||
		status == DeviceStatusBlocked ||
		status == DeviceStatusIgnored
}
